download and validate img before wiping out user data
provided img might be invalid but by the time we find out, the device has already been factory reset and all user data wiped out. That's not good, so now we'll first validate that the img is good before wiping out the data and proceeding with overwriting the system.

diff --git a/common/sbin/signageos-prepareoverwritesystem b/common/sbin/signageos-prepareoverwritesystem
--- a/common/sbin/signageos-prepareoverwritesystem
+++ b/common/sbin/signageos-prepareoverwritesystem
@@ -7,6 +7,12 @@ if [ ! -f "$IMG_URL_FILE" ]; then
     reboot
 fi
 
+IMG_URL=`cat "$IMG_URL_FILE"`
+if ! /sbin/signageos-validateoverwriteimage "$IMG_URL"; then
+    echo "invalid img"
+    reboot
+fi
+
 /sbin/signageos-factoryreset --no-reboot
 mount -o remount,rw /media/mmcblk0p1
 cp "$IMG_URL_FILE" /media/mmcblk0p1/install_img.txt
